# June 2020
# Steve Klosky
# Cohesity
#
# Dockerfile to build production rclone-browser Athena app image
# Assumes 3 files are staged for the build
# Assumes all 3 files are marked as executable before the copy
# rclone executable
# view-mounter-exec
# rclone-ui

FROM alpine:latest

# load rclone onto the image
COPY ./rclone /usr/bin/

# load view-mounter-exec 
COPY ./view-mounter-exec /usr/bin/

# load start script
COPY ./rclone-ui.start /etc/init.d/

#setup entrypoint / startup script
CMD [ "sh", "/etc/init.d/rclone-ui.start" ]
